ims/ims/addons/tracker/urls.py
from django.conf import settings
from django.urls import re_path
from ims.addons.tracker import views
from ims.addons.tracker import reporting_views

app_name='ims.addons.tracker'
urlpatterns = [
    re_path(r'^$', views.home, name='home'),
    re_path(r'^profile/$', views.ajax_profile, name='ajax_profile'),
    re_path(r'^partthreshold/$', views.status_partthreshold_list, name='status_partthreshold_list'),
    re_path(r'^partthreshold/(?P<id>[\d]+)/$', views.status_partthreshold_detail, name='status_partthreshold_detail'),
    re_path(r'^partthreshold/(?P<id>[\d]+)/subscribe/$', views.ajax_partthreshold_subscribe, name='ajax_partthreshold_subscribe'),
    re_path(r'^partthreshold/(?P<id>[\d]+)/unsubscribe/$', views.ajax_partthreshold_unsubscribe, name='ajax_partthreshold_unsubscribe'),
    re_path(r'^partstoragethreshold/$', views.status_partstoragethreshold_list, name='status_partstoragethreshold_list'),
    re_path(r'^partstoragethreshold/(?P<id>[\d]+)/$', views.status_partstoragethreshold_detail, name='status_partstoragethreshold_detail'),
    re_path(r'^partstoragethreshold/(?P<id>[\d]+)/subscribe/$', views.ajax_partstoragethreshold_subscribe, name='ajax_partstoragethreshold_subscribe'),
    re_path(r'^partstoragethreshold/(?P<id>[\d]+)/unsubscribe/$', views.ajax_partstoragethreshold_unsubscribe, name='ajax_partstoragethreshold_unsubscribe'),
    re_path(r'^kitthreshold/$', views.status_kitthreshold_list, name='status_kitthreshold_list'),
    re_path(r'^kitthreshold/(?P<id>[\d]+)/$', views.status_kitthreshold_detail, name='status_kitthreshold_detail'),
    re_path(r'^kitthreshold/(?P<id>[\d]+)/subscribe/$', views.ajax_kitthreshold_subscribe, name='ajax_kitthreshold_subscribe'),
    re_path(r'^kitthreshold/(?P<id>[\d]+)/unsubscribe/$', views.ajax_kitthreshold_unsubscribe, name='ajax_kitthreshold_unsubscribe'),
    re_path(r'^objectaction/$', views.status_objectaction_list, name='status_objectaction_list'),
    re_path(r'^objectaction/(?P<id>[\d]+)/$', views.status_objectaction_detail, name='status_objectaction_detail'),
    re_path(r'^objectaction/(?P<id>[\d]+)/subscribe/$', views.ajax_objectaction_subscribe, name='ajax_objectaction_subscribe'),
    re_path(r'^objectaction/(?P<id>[\d]+)/unsubscribe/$', views.ajax_objectaction_unsubscribe, name='ajax_objectaction_unsubscribe'),
    re_path(r'^emailrecipient/$', views.emailrecipient_list, name='emailrecipient_list'),
    re_path(r'^emailrecipient/(?P<id>[\d]+)/$', views.emailrecipient_detail, name='emailrecipient_detail'),
    re_path(r'^emailtemplate/$', views.emailtemplate_list, name='emailtemplate_list'),
    re_path(r'^emailtemplate/(?P<id>[\d]+)/$', views.emailtemplate_detail, name='emailtemplate_detail'),
    re_path(r'^partthresholdnotify/(?P<id>[\d]+)/delete/$', views.ajax_partthresholdnotify_delete, name='ajax_partthresholdnotify_delete'),
    re_path(r'^partstoragethresholdnotify/(?P<id>[\d]+)/delete/$', views.ajax_partstoragethresholdnotify_delete, name='ajax_partstoragethresholdnotify_delete'),
    re_path(r'^kitthresholdnotify/(?P<id>[\d]+)/delete/$', views.ajax_kitthresholdnotify_delete, name='ajax_kitthresholdnotify_delete'),
    re_path(r'^objectactionnotify/(?P<id>[\d]+)/delete/$', views.ajax_objectactionnotify_delete, name='ajax_objectactionnotify_delete'),
    re_path(r'^reporting/$', reporting_views.reporting_home, name='reporting_home'),
    re_path(r'^reporting/recent/adds/$', reporting_views.reporting_recent_adds, name='reporting_recent_adds'),
    re_path(r'^reporting/recent/mods/$', reporting_views.reporting_recent_mods, name='reporting_recent_mods'),
    re_path(r'^reporting/recent/user/$', reporting_views.reporting_recent_user, name='reporting_recent_user'),
    re_path(r'^reporting/counts/part/$', reporting_views.reporting_counts_part, name='reporting_counts_part'),
    re_path(r'^reporting/counts/storage/$', reporting_views.reporting_counts_storage, name='reporting_counts_storage'),
    re_path(r'^reporting/counts/kit/$', reporting_views.reporting_counts_kit, name='reporting_counts_kit'),
    re_path(r'^reporting/graph/$', reporting_views.reporting_graph, name='reporting_graph'),
    re_path(r'^reporting/graph_models/(?P<model>[\w]+)/$', reporting_views.ajax_graph_models, name='ajax_graph_models'),
    re_path(r'^reporting/report_options/(?P<view>[\w]+)/$', reporting_views.ajax_report_dropdown_options, name='ajax_report_dropdown_options'),
    #re_path(r'^reporting/graph/parthistory/(?P<id>[\d]+)/$', views.ajax_get_historic_part_count, name='ajax_get_historic_part_count'),
    #re_path(r'^reporting/graph/kithistory/(?P<id>[\d]+)/$', views.ajax_get_historic_kit_count, name='ajax_get_historic_kit_count'),
    #re_path(r'^reporting/graph/partstoragehistory/(?P<id>[\d]+)/$', views.ajax_get_historic_partstorage_count, name='ajax_get_historic_partstorage_count'),
    re_path(r'^reporting/scheduler/$', reporting_views.reporting_scheduler, name='reporting_scheduler'),
    re_path(r'^reporting/scheduler/create/$', reporting_views.reporting_scheduler_create, name='reporting_scheduler_create'),
    re_path(r'^reporting/scheduler/view/(?P<id>[\d]+)/$', reporting_views.reporting_scheduler_view, name='reporting_scheduler_view'),
    re_path(r'^reporting/scheduler/change/(?P<id>[\d]+)/$', reporting_views.reporting_scheduler_change, name='reporting_scheduler_change'),
    re_path(r'^reporting/scheduler/delete/(?P<id>[\d]+)/$', reporting_views.ajax_scheduler_delete, name='ajax_scheduler_delete'),
    re_path(r'^reporting/scheduler/subscribe/(?P<id>[\d]+)/$', reporting_views.ajax_scheduler_subscribe, name='ajax_scheduler_subscribe'),
    re_path(r'^reporting/scheduler/unsubscribe/(?P<id>[\d]+)/$', reporting_views.ajax_scheduler_unsubscribe, name='ajax_scheduler_unsubscribe'),
    re_path(r'^reporting/scheduler/assign/(?P<rid>[\d]+)/(?P<uid>[\d]+)/$', reporting_views.ajax_scheduler_assign, name='ajax_scheduler_assign'),
    re_path(r'^reporting/scheduler/unassign/(?P<rid>[\d]+)/(?P<uid>[\d]+)/$', reporting_views.ajax_scheduler_unassign, name='ajax_scheduler_unassign'),

]

ims/ims/addons/tracker/forms.py
from datetime import datetime
from django import forms
from django.contrib.auth.models import User

from inventory.models import Part, Kit, Storage
from ims.addons.tracker.helpers import GRAPH_CHOICES, MODEL_CHOICES, PERIOD_CHOICES, REPORTS, SCHEDULER_CHOICES, SOLAR_CHOICES, TIMESPAN_CHOICES
from ims.addons.tracker.widgets import DateInput, TimeInput

class ModelSelectForm(forms.Form):
    id = forms.MultipleChoiceField(choices = MODEL_CHOICES)

class GraphSelectForm(forms.Form):
    graph = forms.ChoiceField(choices = GRAPH_CHOICES, initial = GRAPH_CHOICES[2])
    id = forms.ModelChoiceField(Part.objects.all())

class MultipurposeSelectForm(forms.Form):
    id = forms.ModelChoiceField(queryset=None)

    def __init__(self, model, *args, **kwargs):
        super(forms.Form, self).__init__(*args, **kwargs)
        self.fields['id'] = forms.ModelChoiceField(queryset=model.objects.all())

class PartMultiSelectForm(forms.Form):
    part = forms.ModelMultipleChoiceField(Part.objects.all())

class KitMultiSelectForm(forms.Form):
    kit = forms.ModelMultipleChoiceField(Kit.objects.all())

class StorageMultiSelectForm(forms.Form):
    storage = forms.ModelMultipleChoiceField(Storage.objects.all())

class TimeSpanForm(forms.Form):
    duration = forms.IntegerField(min_value = 1, initial = 1, max_value = 9223372036854775807)
    span = forms.ChoiceField(choices = TIMESPAN_CHOICES, initial = TIMESPAN_CHOICES[1])

class UserSelectForm(forms.Form):
    user = forms.ModelChoiceField(User.objects.all())

class ReportSchedulerForm(forms.Form):
    name = forms.CharField(max_length = 50)
    description = forms.CharField(max_length = 250)
    report = forms.ChoiceField(choices = REPORTS, initial = REPORTS[9])
    schedule = forms.ChoiceField(choices = SCHEDULER_CHOICES, initial = SCHEDULER_CHOICES[2])

class ClockedScheduleForm(forms.Form):
    date = forms.DateField(required = False, initial = datetime.now(), widget = DateInput)
    time = forms.TimeField(required = False, initial = datetime.now(), widget = TimeInput)
    timezone = forms.CharField(required = False, initial = 'UTC')

class IntervalScheduleForm(forms.Form):
    number = forms.IntegerField(min_value = 1, initial = 1, max_value = 9223372036854775807)
    period = forms.ChoiceField(choices = PERIOD_CHOICES, initial = PERIOD_CHOICES[3])

class CronScheduleForm(forms.Form):
    minute = forms.CharField(required = False, initial = '*')
    hour = forms.CharField(required = False, initial = '*')
    day = forms.CharField(required = False, initial = '*')
    month = forms.CharField(required = False, initial = '*')
    day_of_week = forms.CharField(required = False, initial = '*')
    timezone = forms.CharField(required = False, initial = 'UTC')

class SolarScheduleForm(forms.Form):
    event = forms.ChoiceField(required = False, choices = SOLAR_CHOICES, initial = SOLAR_CHOICES[7])
    latitude = forms.FloatField(required = False, min_value = -90, max_value = 90)
    longitude = forms.FloatField(required = False, min_value = -180, max_value = 180)

ims/templates/tracker/reporting/scheduler/create.html
{% extends "inventory/base.html" %}
{% load static %}
{% load get_setting %}
{% load custom_tags %}
{% block title %}New Scheduled Report{% endblock %}
{% block content %}
<div class="w3-container w3-padding w3-light-gray" style="margin-top:20px;">
    <a href="/tracker/" alt="Tracker">Tracker</a>
    »
    <a href="/tracker/reporting/" alt="Tracker Reporting">Reporting</a>
    »
    <a href="/tracker/reporting/scheduler/" alt="Tracker Scheduled Reports">Scheduled Reports</a>
    » New Scheduled Report
</div>
<div class="w3-container">
    <div class="w3-left w3-margin-top">
        <h4><b>New Scheduled Report</b></h4>
    </div>
    <div class="w3-container">
        <div class="w3-col w3-padding w3-left">{{ message }}</div>
    </div>
    <div class="w3-container">
        <form class="w3-col l12 xl6 w3-card w3-padding w3-bar-block" action="." method="post">
            {% csrf_token %}
            {{ reportform.non_field_errors }}
            {% for field in reportform %}
            <div class="w3-bar-item">
                {{ field.errors }}
                {{ field | add_classes_and_auto_format:"w3-left ims-select-options ims-form-field" }}
            </div>
            {% endfor %}
            {{ timespanform.non_field_errors }}
            {% for field in timespanform %}
            <div class="w3-bar-item">
                {{ field.errors }}
                {{ field | add_classes_and_auto_format:"w3-left ims-select-options ims-form-field" }}
            </div>
            {% endfor %}
            {{ modelform.non_field_errors }}
            {% for field in modelform %}
            {% if field.name == 'id' %}
            <div class="w3-bar-item">
                {{ field.errors }}
                {{ field | add_classes:"w3-left ims-select-options ims-form-field" }}
            </div>
            {% endif %}
            {% endfor %}
            {{ cronform.non_field_errors }}
            {% for field in cronform %}
            <div>
                {{ field.errors }}
                {{ field | add_classes_and_auto_format:"w3-left ims-select-options ims-form-field ims-hidden" }}
            </div>
            {% endfor %}
            {{ solarform.non_field_errors }}
            {% for field in solarform %}
            <div>
                {{ field.errors }}
                {{ field | add_classes_and_auto_format:"w3-left ims-select-options ims-form-field ims-hidden" }}
            </div>
            {% endfor %}
            {{ clockform.non_field_errors }}
            {% for field in clockform %}
            <div>
                {{ field.errors }}
                {{ field | add_classes_and_auto_format:"w3-left ims-select-options ims-form-field ims-hidden" }}
            </div>
            {% endfor %}
            {{ intervalform.non_field_errors }}
            {% for field in intervalform %}
            <div class="w3-bar-item">
                {{ field.errors }}
                {{ field | add_classes_and_auto_format:"w3-left ims-select-options ims-form-field" }}
            </div>
            {% endfor %}
            <div class="w3-bar-item">
                <input type="submit" class="w3-button w3-dark-grey ims-form-field" value="Create">
            </div>
            <div class="w3-bar-item">
                <a href="/tracker/reporting/" class="w3-button w3-light-grey ims-form-field">Cancel</a>
            </div>
        </form>
    </div>
</div>
<script src="{% static "common/js/jquery.min.js" %}"></script>
<script>
    $("#id_schedule").change(function() {
        var schedule = $(this).val();
        hide_not_required("id_time");
        hide_not_required("id_date");
        hide_not_required("id_minute");
        hide_not_required("id_hour");
        hide_not_required("id_day");
        hide_not_required("id_month");
        hide_not_required("id_day_of_week");
        hide_not_required("id_timezone");
        hide_not_required("id_event");
        hide_not_required("id_latitude");
        hide_not_required("id_longitude");
        hide_not_required("id_number");
        hide_not_required("id_period");
        if (schedule === 'c'){
            show_required("id_time");
            show_required("id_date");
        }
        if (schedule === 's'){
            show_required("id_event");
            show_required("id_latitude");
            show_required("id_longitude");
        }
        if (schedule === 't'){
            show_required("id_minute");
            show_required("id_hour");
            show_required("id_day");
            show_required("id_month");
            show_required("id_day_of_week");
            show_required("id_timezone");
        }
        if (schedule === 'i'){
            show_required("id_number");
            show_required("id_period");
        }
    })
    function hide_not_required(field_id){
        elem = document.getElementById(field_id);
        elem.required = NaN;
        elem.parentNode.classList.remove("w3-bar-item");
        $("#"+field_id).addClass("ims-hidden");
    }
    function show_required(field_id){
        elem = document.getElementById(field_id);
        elem.required = true;
        elem.parentNode.classList.add("w3-bar-item");
        $("#"+field_id).removeClass("ims-hidden");
    }
    $("#id_report").change(function() {
        var report = $(this).val();
        var model = '';
        var options = '';
        document.getElementById("id_id").multiple = NaN;
        if (report.slice(-4) === 'list'){
            $("#id_duration").removeClass("ims-hidden");
            $("#id_span").removeClass("ims-hidden");
            options = report;
            if (report != 'recent_user_list'){
                document.getElementById("id_id").multiple = true;
            }
        } else if (report.slice(0,8) === 'historic') {
            $("#id_duration").removeClass("ims-hidden");
            $("#id_span").removeClass("ims-hidden");
            if (report === 'historic_kit_count_graph' || report === 'historic_kit_count'){ model = 'hkcl'; }
            if (report === 'historic_part_count_graph' || report === 'historic_part_count'){ model = 'hpcl'; }
            if (report === 'historic_partstorage_count_graph' || report === 'historic_partstorage_count'){ model = 'hpscl'; }
        } else {
            $("#id_duration").addClass("ims-hidden");
            $("#id_duration").val("1");
            $("#id_span").addClass("ims-hidden");
            $("#id_span").val("h");
            if (report === 'storage_counts_graph' || report === 'storage_counts'){ model = 'scb'; }
            if (report === 'part_counts_graph' || report === 'part_counts'){
                model = 'pcb';
                document.getElementById("id_id").multiple = true;
            }
            if (report === 'kit_counts_graph' || report === 'kit_counts'){
                model = 'kcb';
                document.getElementById("id_id").multiple = true;
            }
        }
        if (model != ''){
            $.ajax({
                'url': '/tracker/reporting/graph_models/' + model + '/',
                success: function(data){
                    $("#id_id").html(data);
                }
            })
        }
        if (options != ''){
            $.ajax({
                'url': '/tracker/reporting/report_options/' + options + '/',
                success: function(data){
                    $("#id_id").html(data);
                }
            })
        }
    })
</script>
{% endblock %}

ims/templates/tracker/reporting/scheduler/update.html
{% extends "inventory/base.html" %}
{% load static %}
{% load get_setting %}
{% load custom_tags %}
{% block title %}Update Scheduled Report{% endblock %}
{% block content %}
<div class="w3-container w3-padding w3-light-gray" style="margin-top:20px;">
    <a href="/tracker/" alt="Tracker">Tracker</a>
    »
    <a href="/tracker/reporting/" alt="Tracker Reporting">Reporting</a>
    »
    <a href="/tracker/reporting/scheduler/" alt="Tracker Scheduled Reports">Scheduled Reports</a>
    » Update Scheduled Report
</div>
<div class="w3-container">
    <div class="w3-left w3-margin-top">
        <h4><b>Update Scheduled Report</b></h4>
    </div>
    <div class="w3-container">
        <div class="w3-col w3-padding w3-left">{{ message }}</div>
    </div>
    <div class="w3-container">
        <form class="w3-col l12 xl6 w3-card w3-padding w3-bar-block" action="." method="post">
            {% csrf_token %}
            {{ reportform.non_field_errors }}
            {% for field in reportform %}
            <div class="w3-bar-item">
                {{ field.errors }}
                {{ field | add_classes_and_auto_format:"w3-left ims-select-options ims-form-field" }}
            </div>
            {% endfor %}
            {{ timespanform.non_field_errors }}
            {% for field in timespanform %}
            <div class="w3-bar-item">
                {{ field.errors }}
                {{ field | add_classes_and_auto_format:"w3-left ims-select-options ims-form-field" }}
            </div>
            {% endfor %}
            {{ modelform.non_field_errors }}
            {% for field in modelform %}
            {% if field.name == 'id' %}
            <div class="w3-bar-item">
                {{ field.errors }}
                {{ field | add_classes:"w3-left ims-select-options ims-form-field" }}
            </div>
            {% endif %}
            {% endfor %}
            {{ cronform.non_field_errors }}
            {% for field in cronform %}
            {% if visible == "crontab" %}
            <div class="w3-bar-item">
                {{ field.errors }}
                {{ field | add_classes_and_auto_format:"w3-left ims-select-options ims-form-field" }}
            {% else %}
            <div>
                {{ field.errors }}
                {{ field | add_classes_and_auto_format:"w3-left ims-select-options ims-form-field ims-hidden" }}
            {% endif %}
            </div>
            {% endfor %}
            {{ solarform.non_field_errors }}
            {% for field in solarform %}
            {% if visible == "solar" %}
            <div class="w3-bar-item">
                {{ field.errors }}
                {{ field | add_classes_and_auto_format:"w3-left ims-select-options ims-form-field" }}
            {% else %}
            <div>
                {{ field.errors }}
                {{ field | add_classes_and_auto_format:"w3-left ims-select-options ims-form-field ims-hidden" }}
            {% endif %}
            </div>
            {% endfor %}
            {{ clockform.non_field_errors }}
            {% for field in clockform %}
            {% if visible == "clocked" %}
            <div class="w3-bar-item">
                {{ field.errors }}
                {{ field | add_classes_and_auto_format:"w3-left ims-select-options ims-form-field" }}
            {% else %}
            <div>
                {{ field.errors }}
                {{ field | add_classes_and_auto_format:"w3-left ims-select-options ims-form-field ims-hidden" }}
            {% endif %}
            </div>
            {% endfor %}
            {{ intervalform.non_field_errors }}
            {% for field in intervalform %}
            {% if visible == "interval" %}
            <div class="w3-bar-item">
                {{ field.errors }}
                {{ field | add_classes_and_auto_format:"w3-left ims-select-options ims-form-field" }}
            {% else %}
            <div>
                {{ field.errors }}
                {{ field | add_classes_and_auto_format:"w3-left ims-select-options ims-form-field ims-hidden" }}
            {% endif %}
            </div>
            {% endfor %}
            <div class="w3-bar-item">
                <input type="submit" class="w3-button w3-dark-grey ims-form-field" value="Update">
            </div>
            <div class="w3-bar-item">
                <a href="/tracker/reporting/" class="w3-button w3-light-grey ims-form-field">Cancel</a>
            </div>
        </form>
    </div>
</div>
<div class="w3-container">
    <div class="w3-left w3-margin-top">
        <b>Subscribed Users</b>
    </div>
    <div class="w3-container">
        <div id="submessage" class="w3-col w3-padding w3-left"></div>
    </div>
    <div class="w3-container">
        {% for recipient in recipients %}
        <div id="{{ recipient.id }}" class="w3-card w3-padding w3-left w3-col">
            <div class="w3-left"><b>{{ recipient.name }}</b></div>
            <div class="w3-right"><a id="{{ recipient.id }}-subscribe" onclick="subscription({{ recipient.id }})" alt="Toggle recipient '{{ recipient.name }}' for notifications" class="{% if recipient.subscribed %}w3-hover-red{% else %}w3-hover-green{% endif %} w3-padding w3-round w3-border w3-margin-right">{% if recipient.subscribed %}Una{% else %}A{% endif %}ssign</a></div>
        </div>
        {% endfor %}
    </div>
</div>
<script src="{% static "common/js/jquery.min.js" %}"></script>
<script>
    function hide_not_required(field_id){
        elem = document.getElementById(field_id);
        elem.required = NaN;
        elem.parentNode.classList.remove("w3-bar-item");
        $("#"+field_id).addClass("ims-hidden");
    }
    function show_required(field_id){
        elem = document.getElementById(field_id);
        elem.required = true;
        elem.parentNode.classList.add("w3-bar-item");
        $("#"+field_id).removeClass("ims-hidden");
    }
    function update_schedule_view(field_ids){
        all_fields = ["id_time","id_date","id_minute","id_day","id_month","id_day_of_week","id_timezone","id_event","id_latitude","id_longitude","id_number","id_period"];
        for (let i = 0; i < field_ids.length; i++){
            index = all_fields.indexOf(field_ids[i]);
            if (index > -1){
                all_fields.splice(index, 1)
                show_required(field_ids[i]);
            }
        }
        all_fields.forEach(hide_not_required)
    }
    $("#id_schedule").change(function (){
        schedule = $(this).val()
        if (schedule === 'c'){
            update_schedule_view(["id_time","id_date"]);
        }
        if (schedule === 's'){
            update_schedule_view(["id_event","id_latitude","id_longitude"]);
        }
        if (schedule === 't'){
            update_schedule_view(["id_minute","id_hour","id_day","id_month","id_day_of_week","id_timezone"]);
        }
        if (schedule === 'i'){
            update_schedule_view(["id_number","id_period"]);
        }
    })
    $("#id_report").change(function() {
        var report = $(this).val();
        var model = '';
        var options = '';
        document.getElementById("id_id").multiple = NaN;
        if (report.slice(-4) === 'list'){
            $("#id_duration").removeClass("ims-hidden");
            $("#id_span").removeClass("ims-hidden");
            options = report;
            if (report != 'recent_user_list'){
                document.getElementById("id_id").multiple = true;
            }
        } else if (report.slice(0,8) === 'historic') {
            $("#id_duration").removeClass("ims-hidden");
            $("#id_span").removeClass("ims-hidden");
            if (report === 'historic_kit_count_graph' || report === 'historic_kit_count'){ model = 'hkcl'; }
            if (report === 'historic_part_count_graph' || report === 'historic_part_count'){ model = 'hpcl'; }
            if (report === 'historic_partstorage_count_graph' || report === 'historic_partstorage_count'){ model = 'hpscl'; }
        } else {
            $("#id_duration").addClass("ims-hidden");
            $("#id_duration").val("1");
            $("#id_span").addClass("ims-hidden");
            $("#id_span").val("h");
            if (report === 'storage_counts_graph' || report === 'storage_counts'){ model = 'scb'; }
            if (report === 'part_counts_graph' || report === 'part_counts'){
                model = 'pcb';
                document.getElementById("id_id").multiple = true;
            }
            if (report === 'kit_counts_graph' || report === 'kit_counts'){
                model = 'kcb';
                document.getElementById("id_id").multiple = true;
            }
        }
        if (model != ''){
            $.ajax({
                'url': '/tracker/reporting/graph_models/' + model + '/',
                success: function(data){
                    $("#id_id").html(data);
                }
            })
        }
        if (options != ''){
            $.ajax({
                'url': '/tracker/reporting/report_options/' + options + '/',
                success: function(data){
                    $("#id_id").html(data);
                }
            })
        }
    })
    function subscription(id) {
        var element = document.getElementById(id + "-subscribe");
        var arr = window.location.pathname.split('/');
        var rid = arr[arr.length -2];
        if (element.text === 'Unassign') {
            $.ajax({
                url: '/tracker/reporting/scheduler/unassign/' + rid + '/' + id + '/',
                type: 'get',
                success: function(data) {
                    if (data.includes('green')) {
                        element.classList.remove('w3-hover-red');
                        element.classList.add('w3-hover-green');
                        element.text = 'Assign';
                    }
                    $("#submessage").html(data);
                }
            });
        } else {
            $.ajax({
                url: '/tracker/reporting/scheduler/assign/' + rid + '/' + id + '/',
                type: 'get',
                success: function(data) {
                    if (data.includes('green')) {
                        element.classList.remove('w3-hover-green');
                        element.classList.add('w3-hover-red');
                        element.text = 'Unassign';
                    }
                    $("#submessage").html(data);
                }
            });
        }
    }
</script>
{% endblock %}